- name: Roboshop  automated Jenkins job creation
  hosts: localhost
  connection: local
  vars:
    sb_jobs:
      - Roboshop-Terraform
#    mb_jobs:
#      - catalogue
#      - cart
#      - user
#      - shipping
#      - payment
#      - frontend
#      - dispatch
  roles:
    - jenkins-jobs
      