- name: Roboshop  automated Jenkins job creation
  hosts: localhost
  connection: local
  vars:
    jobs:
      - Roboshop-Terraform
      - catalogue
      - payment
  roles:
    - jenkins-jobs
      