- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/home/centos/Roboshop-Jenkins/roles/jenkins-jobs/templates/pipeline.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://172.31.88.247:8080
    user: admin