- name: Setup of Single branch jenkins jobs
  ansible.builtin.include_tasks:
   file: sb_job.yml
  loop: "{{sb_jobs}}"

- name: Setup of multi branch jenkins jobs
  ansible.builtin.include_tasks:
    file: mb_job.yml
  loop: "{{mb_jobs}}"

