- name: Setup Template
  ansible.builtin.template:
    src: sbranch_pipeline.xml
    dest: /tmp/sbranch_pipeline.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sbranch_pipeline.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://172.31.88.247:8080
    user: admin